//working
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthProvider } from "./providers";
import { LanguageProvider } from "./contexts/LanguageContext";
import CookieConsentPopup from "./components/CookieConsent";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Joyk Multiservices Group",
  description:
    "We specialize in offering reliable and convenient cab services for seamless travel between the Blaise Diagne International Airport, Senegal, and any city in Senegal, as well as from any city in Senegal to the Blaise Diagne International Airport, Senegal.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <!-- Google tag (gtag.js) --> */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-0TTDYNNEJ5"
          strategy="afterInteractive"
        ></Script>
        <Script id="google-analytics" strategy="afterInteractive">
          {` window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-0TTDYNNEJ5');`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <LanguageProvider>
            <Navbar />
            {children}
            <Footer />
            <CookieConsentPopup />
          </LanguageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return children;
// }
